### ISSUE TITLE
Test is failing

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2et#21]
This test is failing because no warning is generated.  I'm not sure if the test should be removed or the warning should be added back in.

https://github.com/nlmixr2/rxode2et/blob/e3592f9821272025a7953c099126a79657c47d48/tests/testthat/test-et.R#L588-L591

**Comment by mattfidler** [comment]
Your right.

It is fixed in one of the pull requests needed to move etTrans to rxode2parse
