### ISSUE TITLE
Reading dataset with 'rate' = -2

### ISSUE THREAD

**Issue by JohanWBorg** [nlmixr2/rxode2et#33]
Hi!
I've encountered a possible bug in RxODE2 while trying to read a dataset with a rate column with a value of either -1 or -2. My dataset is looking like the following (subset of only one individual) : 
```
id  time  amt rate
1   0.0 25.0   -2
1   2.0  0.0    0
1  12.5  3.5   -2
1  24.5  3.5   -2
1  37.0  3.5   -2
1  48.0  3.5   -2
1  60.5  3.5   -2
1  72.5  3.5   -2
1  85.3  3.5   -2
1  96.5  3.5   -2
1 108.5  3.5   -2
1 112.5  0.0    0
```
Converting this to an event table using `et()` seems to ignore the 'rate' column
```
      id  time   amt evid         
   <int> <dbl> <dbl> <evid>       
 1     1   0    25   1:Dose (Add) 
 2     1   2    NA   0:Observation
 3     1  12.5   3.5 1:Dose (Add) 
 4     1  24.5   3.5 1:Dose (Add) 
 5     1  37     3.5 1:Dose (Add) 
 6     1  48     3.5 1:Dose (Add) 
 7     1  60.5   3.5 1:Dose (Add) 
 8     1  72.5   3.5 1:Dose (Add) 
 9     1  85.3   3.5 1:Dose (Add) 
10     1  96.5   3.5 1:Dose (Add) 
.
.
.
```
This differs from how the EventTable looks like in the [RxODE2 manual](https://nlmixr2.github.io/rxode2/articles/rxode2-event-types.html#modeled-rate-and-duration-of-infusion), where the rate column is also present with a value of -2.

I believe this might be a bug because if the value in the 'rate' column is changed to something positive (and hence not -2 or -1) it is correctly translated to the EventTable. Please take a look at the example below.
```
id  time  amt rate
1   0.0 25.0   2
1   2.0  0.0    0
1  12.5  3.5   2
1  24.5  3.5   2
1  37.0  3.5   2
1  48.0  3.5   2
1  60.5  3.5   2
1  72.5  3.5   2
1  85.3  3.5   2
1  96.5  3.5   2
1 108.5  3.5   2
1 112.5  0.0    0

et(dataset)

      id  time   amt rate       evid         
   <int> <dbl> <dbl> <rate/dur> <evid>       
 1     1   0    25    2         1:Dose (Add) 
 2     1   2    NA   NA         0:Observation
 3     1  12.5   3.5  2         1:Dose (Add) 
 4     1  24.5   3.5  2         1:Dose (Add) 
 5     1  37     3.5  2         1:Dose (Add) 
 6     1  48     3.5  2         1:Dose (Add) 
 7     1  60.5   3.5  2         1:Dose (Add) 
 8     1  72.5   3.5  2         1:Dose (Add) 
 9     1  85.3   3.5  2         1:Dose (Add) 
10     1  96.5   3.5  2         1:Dose (Add) 
.
.
.
```
Naturally, with the missing rate column, the values of the results are off when trying to run a model on the dataset. I would much appreciate any comments or insights as to why the modeled rate seems to be missing. 

Please let me know if there is any more information I can provide and many thanks in advance.

**Comment by mattfidler** [comment]
Thanks for reporting!

**Comment by JohanWBorg** [comment]
Amazing! Thank you so much. I'll try it out as soon as possible.
